# wrangler.toml

name = "paperg"
pages_build_output_dir = "public"
compatibility_date = "2025-04-06" # 保持或更新兼容性日期

# [[kv_namespaces]] ... (保持你的 KV 绑定配置)
[[kv_namespaces]]
binding = "KV_NAMESPACE"
id = "1807ae37a2c94916add2181d8a20125a" # 或者 preview_id

# --- 生产环境变量 ---
# 这些变量会在部署到 Cloudflare Pages 时生效
[vars]
API_ENDPOINT = "https://api.deepseek.com/v1" # 替换为你的生产 API Endpoint
LLM_MODEL = "deepseek-reasoner"                     # 替换为你的生产模型名称
SYSTEM_PROMPT = """不必输出思考过程，只需要输出优化结果。""" # 你的生产系统提示