# wrangler.toml

name = "paperg"
pages_build_output_dir = "public"
compatibility_date = "2025-04-06" # 保持或更新兼容性日期

# [[kv_namespaces]] ... (保持你的 KV 绑定配置)
[[kv_namespaces]]
binding = "KV_NAMESPACE"
id = "4dcd1b2c5cf94fbeb5fe79f53fdf6fc4" # 或者 preview_id

# --- 生产环境变量 ---
# 这些变量会在部署到 Cloudflare Pages 时生效
[vars]
API_ENDPOINT = "https://api.tu-zi.com/v1" # 替换为你的生产 API Endpoint
LLM_MODEL = "grok-3"                     # 替换为你的生产模型名称
SYSTEM_PROMPT = "You are a helpful assistant." # 你的生产系统提示